name: Build & Push Docker Image

on:
  push:
    branches:
      - master
    paths:
      - 'Dockerfile'
      - '.github/workflows/docker.yml'
  pull_request:
    branches:
      - master
    paths:
      - 'Dockerfile'
      - '.github/workflows/docker.yml'

jobs:
  publish_images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push multi-arch image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/porotech-frontend:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/porotech-frontend:${{ github.sha }}

      - name: Wait for HTTP health endpoint
        run: |
          for i in $(seq 1 10); do
            if curl --silent --fail http://localhost:8080/healthcheck; then
              echo "✅ Service is healthy!"
              exit 0
            fi
            echo "Waiting for service… ($i/10)"
            sleep 5
          done
          echo "::error::Service never became available"
          docker logs porotech-test
          exit 1

      - name: Teardown test container
        if: always()
        run: |
          docker stop porotech-test || true